name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  pr-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Configure pip
        run: |
          python -m pip install --upgrade pip
          pip config set global.extra-index-url https://uvx.org/pypi/simple/

      - name: Install dependencies
        run: npm ci

      - name: Run PR check script
        run: npm run pr-check
        env:
          DEBUG: 'true'

      - name: Provide feedback
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            COMMENT="✅ PR validation passed successfully!"
          else
            COMMENT="❌ PR validation failed. Please check the workflow logs for details."
          fi
          gh pr comment ${{ github.event.pull_request.number }} --body "$COMMENT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
